### ISSUE TITLE
flac-libs 1.4.3 pulls in unwanted development files

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/rpm-specs#12]
Trying to upgrade flac-libs tries to also install autoconf, automake, flac-devel, libogg-devel and perl-Data-Dumper. Is this really neccessary?

**Comment by TeLLie** [comment]
Hi David
Please do a Yum update 2>&1 |tee stdout.txt
and listed here.
As normally the build requires not be installed.

**Comment by DavidMcKenna** [comment]
Seems there is a newer version now - I did as you ask and it worked without adding extra development parts... thanks!

**Comment by TeLLie** [comment]
David,
Ok, good it works now.
I close this issue.
